# Generated by Django 4.2.1 on 2023-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cat', models.CharField(choices=[('1', 'Crop production'), ('2', 'Animal Production'), ('3', 'Processing')], default=True, max_length=200)),
                ('doe', models.DateField(verbose_name='Date of Establishment')),
            ],
        ),
    ]
